// src/features/users/utils/reportExport.ts
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { User, deriveStatus } from "../types";

export interface ReportFilters {
    userType: "all" | "clients" | "bidders";
    status: "all" | "active" | "suspended";
    location: string; // "all" or a specific location name
    dateFrom: string; // yyyy-mm-dd or ""
    dateTo: string;   // yyyy-mm-dd or ""
}

export interface ReportMeta {
    title: string;
    generatedBy: string;
    generatedOn: Date;
    filters: ReportFilters;
    totalCount: number;
}

const REPORT_COLUMNS = [
    { label: "User Name" },
    { label: "Email" },
    { label: "Phone" },
    { label: "Location" },
    { label: "User Type" },
    { label: "Status" },
    { label: "Joined" },
];

const capitalize = (s: string): string => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s);

const userTypeLabel = (u: User): string => {
    const names = (u.user_type_names ?? []).map((t) => t.toLowerCase());
    const labels: string[] = [];
    if (names.includes("hire talent")) labels.push("Client");
    if (names.includes("find work")) labels.push("Bidder");
    return labels.length ? labels.join(", ") : "—";
};

const userLocation = (u: User): string =>
    (u.location_names && u.location_names.length ? u.location_names.join(", ") : u.location) || "—";

const toReportRow = (u: User): string[] => [
    u.name || "—",
    (u as any).email || "—",
    u.phone || "—",
    userLocation(u),
    userTypeLabel(u),
    capitalize(deriveStatus(u)),
    u.created_at ? new Date(u.created_at).toLocaleDateString("en-GB") : "—",
];

/* ── filtering ────────────────────────────────────────────────── */
export const filterUsersForReport = (users: User[], filters: ReportFilters): User[] => {
    let list = users;

    if (filters.userType !== "all") {
        const want = filters.userType === "clients" ? "hire talent" : "find work";
        list = list.filter((u) => (u.user_type_names ?? []).map((t) => t.toLowerCase()).includes(want));
    }

    if (filters.status !== "all") {
        list = list.filter((u) => deriveStatus(u) === filters.status);
    }

    if (filters.location !== "all") {
        list = list.filter((u) => (u.location_names ?? []).includes(filters.location));
    }

    if (filters.dateFrom) {
        const from = new Date(filters.dateFrom);
        list = list.filter((u) => u.created_at && new Date(u.created_at) >= from);
    }

    if (filters.dateTo) {
        const to = new Date(filters.dateTo);
        to.setHours(23, 59, 59, 999);
        list = list.filter((u) => u.created_at && new Date(u.created_at) <= to);
    }

    return list;
};

export const formatFiltersSummary = (filters: ReportFilters): string => {
    const parts: string[] = [];
    parts.push(`User Type: ${filters.userType === "all" ? "All" : filters.userType === "clients" ? "Client" : "Bidder"}`);
    parts.push(`Status: ${filters.status === "all" ? "All" : capitalize(filters.status)}`);
    parts.push(`Location: ${filters.location === "all" ? "All" : filters.location}`);
    const range =
        filters.dateFrom || filters.dateTo
            ? `${filters.dateFrom || "…"} – ${filters.dateTo || "…"}`
            : "All time";
    parts.push(`Date Range: ${range}`);
    return parts.join("   •   ");
};

const formatDateTime = (d: Date): string =>
    d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });

const dateStamp = (): string => new Date().toISOString().slice(0, 10);

const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/* ── CSV ──────────────────────────────────────────────────────── */
const csvEscape = (val: string): string =>
    /[",\n]/.test(val) ? `"${val.replace(/"/g, '""')}"` : val;

export const exportUsersCSV = (users: User[], meta: ReportMeta) => {
    const lines: string[] = [];
    lines.push(csvEscape(meta.title));
    lines.push(`Generated By:,${csvEscape(meta.generatedBy)}`);
    lines.push(`Generated On:,${csvEscape(formatDateTime(meta.generatedOn))}`);
    lines.push(`Filters:,${csvEscape(formatFiltersSummary(meta.filters))}`);
    lines.push(`Total Users:,${meta.totalCount}`);
    lines.push("");
    lines.push(REPORT_COLUMNS.map((c) => csvEscape(c.label)).join(","));
    users.forEach((u) => lines.push(toReportRow(u).map(csvEscape).join(",")));

    const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" });
    downloadBlob(blob, `weera-users-report-${dateStamp()}.csv`);
};

/* ── PDF ──────────────────────────────────────────────────────── */
export const exportUsersPDF = (users: User[], meta: ReportMeta) => {
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.setTextColor(234, 88, 12); // ORANGE
    doc.text(meta.title, 14, 18);

    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42); // NAVY
    doc.text(`Generated By: ${meta.generatedBy}`, 14, 27);
    doc.text(`Generated On: ${formatDateTime(meta.generatedOn)}`, 14, 33);

    doc.setTextColor(100, 116, 139); // SLATE
    const filterLines = doc.splitTextToSize(`Filters: ${formatFiltersSummary(meta.filters)}`, 180);
    doc.text(filterLines, 14, 39);

    const afterFiltersY = 39 + filterLines.length * 5;
    doc.setTextColor(15, 23, 42);
    doc.text(`Total Users: ${meta.totalCount}`, 14, afterFiltersY + 2);

    doc.setDrawColor(226, 232, 240);
    doc.line(14, afterFiltersY + 7, 196, afterFiltersY + 7);

    autoTable(doc, {
        startY: afterFiltersY + 12,
        head: [REPORT_COLUMNS.map((c) => c.label)],
        body: users.map(toReportRow),
        styles: { fontSize: 8, textColor: [51, 65, 85] },
        headStyles: { fillColor: [234, 88, 12], textColor: 255, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        margin: { left: 14, right: 14 },
    });

    doc.save(`weera-users-report-${dateStamp()}.pdf`);
};