// src/utils/tableExport.ts
// Shared CSV / PDF writer for admin reports. Callers supply the header block and rows.

export interface ExportMeta {
    title: string;
    generatedBy: string;
    generatedOn: Date;
    filtersSummary: string;
    totalLabel: string;
    totalCount: number;
    fileBase: string;
}

async function loadPdfKit() {
    const [pdfMod, autoTableMod] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
    return { jsPDF: pdfMod.jsPDF, autoTable: autoTableMod.default };
}

export const formatDateTime = (d: Date): string =>
    d.toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });

const dateStamp = (): string => new Date().toISOString().slice(0, 10);

const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    // Safari cancels the download if the URL is revoked in the same tick.
    setTimeout(() => URL.revokeObjectURL(url), 1000);
};

const csvEscape = (val: string): string =>
    /[",\r\n]/.test(val) ? `"${val.replace(/"/g, '""')}"` : val;

export const exportTableCSV = (meta: ExportMeta, headers: string[], rows: string[][]) => {
    const lines = [
        csvEscape(meta.title),
        `Generated By:,${csvEscape(meta.generatedBy)}`,
        `Generated On:,${csvEscape(formatDateTime(meta.generatedOn))}`,
        `Filters:,${csvEscape(meta.filtersSummary)}`,
        `${meta.totalLabel}:,${meta.totalCount}`,
        "",
        headers.map(csvEscape).join(","),
        ...rows.map((r) => r.map(csvEscape).join(",")),
    ];
    // BOM so Excel reads the file as UTF-8.
    const blob = new Blob(["﻿" + lines.join("\r\n")], { type: "text/csv;charset=utf-8;" });
    downloadBlob(blob, `${meta.fileBase}-${dateStamp()}.csv`);
};

// jsPDF's built-in fonts only cover Latin-1; anything else prints as garbage.
const pdfSafe = (val: string): string =>
    val
        .replace(/[–—]/g, "-")
        .replace(/•/g, "|")
        .replace(/…/g, "...")
        .replace(/[‘’]/g, "'")
        .replace(/[“”]/g, '"')
        .normalize("NFD")
        .replace(/[̀-ͯ]/g, "")
        .replace(/[^\n\t\x20-\xFF]/g, "?");

export const exportTablePDF = async (
    meta: ExportMeta,
    headers: string[],
    rows: string[][],
    orientation: "portrait" | "landscape" = "portrait"
) => {
    const { jsPDF, autoTable } = await loadPdfKit();
    const doc = new jsPDF({ orientation });
    const pageW = doc.internal.pageSize.getWidth();
    const left = 14;
    const right = pageW - 14;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(15, 23, 42);
    doc.text(pdfSafe(meta.title), left, 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(pdfSafe(`Generated by ${meta.generatedBy} on ${formatDateTime(meta.generatedOn)}`), left, 25);
    const filterLines = doc.splitTextToSize(pdfSafe(`Filters: ${meta.filtersSummary}`), right - left);
    doc.text(filterLines, left, 31);

    const y = 31 + filterLines.length * 4.5;
    doc.setTextColor(15, 23, 42);
    doc.text(`${meta.totalLabel}: ${meta.totalCount}`, left, y + 1);

    doc.setDrawColor(226, 232, 240);
    doc.line(left, y + 5, right, y + 5);

    autoTable(doc, {
        startY: y + 9,
        head: [headers],
        body: rows.map((r) => r.map(pdfSafe)),
        styles: { fontSize: 8, textColor: [51, 65, 85], cellPadding: 2.5, lineColor: [226, 232, 240], lineWidth: 0.1 },
        headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: "bold" },
        margin: { left, right: 14 },
        didDrawPage: () => {
            const n = doc.getNumberOfPages();
            doc.setFontSize(8);
            doc.setTextColor(148, 163, 184);
            doc.text(`Page ${n}`, right, doc.internal.pageSize.getHeight() - 8, { align: "right" });
        },
    });

    doc.save(`${meta.fileBase}-${dateStamp()}.pdf`);
};
