import React, { useEffect, useMemo, useState } from "react";
import { fetchReportsData } from "../api/reportService";
import {
  formatCurrency,
  formatDateTime,
  ReportColumn,
  ReportTable,
  StatusCell,
  UserCell,
} from "../components/table/ReportTable";
import { ReportSummaryBar } from "../components/table/ReportSummaryBar";
import { ReportToolbar } from "../components/table/ReportToolbar";
import { useReports } from "../hooks/useReports";
import type {
  DisputeReportRow,
  JobPostingReportRow,
  PayoutReportRow,
  ReportRow,
  ReportTabId,
  ReportsData,
  RevenueReportRow,
  TransactionReportRow,
  UserRegistrationReportRow,
} from "../types";

const tabs: { id: ReportTabId; label: string }[] = [
  { id: "transactions", label: "Transaction" },
  { id: "platformRevenue", label: "Platform Revenue" },
  { id: "payouts", label: "Payout" },
  { id: "userRegistrations", label: "User Registration" },
  { id: "jobPostings", label: "Job Posting" },
  { id: "disputes", label: "Dispute Resolution" },
];

const emptyReportsData: ReportsData = {
  transactions: [],
  platformRevenue: [],
  payouts: [],
  userRegistrations: [],
  jobPostings: [],
  disputes: [],
};

const getDateFromRow = (row: ReportRow): string | null => {
  if ("dateTime" in row) return row.dateTime;
  if ("registrationDate" in row) return row.registrationDate;
  if ("postedDate" in row) return row.postedDate;
  if ("createdAt" in row) return row.createdAt;
  return null;
};

const isWithinRange = (iso: string | null, range: string): boolean => {
  if (range === "all") return true;
  if (!iso) return false;

  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return false;

  const now = new Date();
  const start = new Date(now);

  if (range === "7d") {
    start.setDate(now.getDate() - 7);
    return date >= start;
  }

  if (range === "30d") {
    start.setDate(now.getDate() - 30);
    return date >= start;
  }

  if (range === "1y") {
    return date.getFullYear() === now.getFullYear();
  }

  return true;
};

const getStatusFromRow = (row: ReportRow): string => {
  if ("status" in row) return row.status;
  return "";
};

const getSecondaryValue = (row: ReportRow, activeTab: ReportTabId): string => {
  switch (activeTab) {
    case "transactions":
      return "type" in row ? row.type : "";
    case "platformRevenue":
      return "revenueSource" in row ? row.revenueSource : "";
    case "payouts":
      return "method" in row ? row.method : "";
    case "userRegistrations":
      return "userType" in row ? row.userType : "";
    case "jobPostings":
      return "jobTitle" in row ? row.jobTitle : "";
    case "disputes":
      return "reason" in row ? row.reason : "";
    default:
      return "";
  }
};

const getRowsForTab = (data: ReportsData, tab: ReportTabId): ReportRow[] => {
  return data[tab];
};

const getSecondaryPlaceholder = (activeTab: ReportTabId): string => {
  switch (activeTab) {
    case "transactions":
      return "Transaction Type";
    case "platformRevenue":
      return "Revenue Source";
    case "payouts":
      return "Payout Method";
    case "userRegistrations":
      return "User Type";
    case "jobPostings":
      return "Job";
    case "disputes":
      return "Reason";
    default:
      return "Filter";
  }
};

const getReportTitle = (activeTab: ReportTabId): string => {
  switch (activeTab) {
    case "transactions":
      return "Weera Transaction Report";
    case "platformRevenue":
      return "Weera Platform Revenue Report";
    case "payouts":
      return "Weera Payout Report";
    case "userRegistrations":
      return "Weera User Registration Report";
    case "jobPostings":
      return "Weera Job Posting Report";
    case "disputes":
      return "Weera Dispute Resolution Report";
    default:
      return "Weera Report";
  }
};

const getSummaryItems = (activeTab: ReportTabId, rows: ReportRow[]) => {
  const totalAmount = rows.reduce((sum, row) => {
    if ("amount" in row) return sum + row.amount;
    if ("budget" in row) return sum + row.budget;
    return sum;
  }, 0);

  const baseItems = [
    { label: "Generated By", value: "Admin Name" },
    { label: "Date Range", value: "Supabase data" },
  ];

  switch (activeTab) {
    case "transactions":
      return [
        ...baseItems,
        { label: "Total Transactions", value: String(rows.length) },
        { label: "Total Transaction Value", value: formatCurrency(totalAmount) },
      ];
    case "platformRevenue":
      return [
        ...baseItems,
        { label: "Total Revenue", value: formatCurrency(totalAmount) },
      ];
    case "payouts":
      return [
        ...baseItems,
        { label: "Total Payout", value: formatCurrency(totalAmount) },
      ];
    case "userRegistrations":
      return [
        ...baseItems,
        { label: "Total New User", value: rows.length.toLocaleString("en-US") },
      ];
    case "jobPostings":
      return [
        ...baseItems,
        { label: "Total Jobs", value: rows.length.toLocaleString("en-US") },
        { label: "Total Budget", value: formatCurrency(totalAmount) },
      ];
    case "disputes":
      return [
        ...baseItems,
        { label: "Total Disputes", value: rows.length.toLocaleString("en-US") },
      ];
    default:
      return baseItems;
  }
};

const exportCsv = (filename: string, rows: ReportRow[]) => {
  const headers = Array.from(
    rows.reduce((keys, row) => {
      Object.keys(row).forEach((key) => keys.add(key));
      return keys;
    }, new Set<string>())
  );

  const csvRows = [
    headers.join(","),
    ...rows.map((row) =>
      headers
        .map((header) => {
          const value = (row as unknown as Record<string, unknown>)[header];
          const text =
            typeof value === "object" && value !== null
              ? JSON.stringify(value)
              : String(value ?? "");
          return `"${text.replace(/"/g, '""')}"`;
        })
        .join(",")
    ),
  ];

  const blob = new Blob([csvRows.join("\n")], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(url);
};

const getColumns = (activeTab: ReportTabId): ReportColumn<ReportRow>[] => {
  switch (activeTab) {
    case "transactions":
      return [
        { key: "transactionId", label: "Transaction Id" },
        { key: "dateTime", label: "Date & Time", render: (row) => formatDateTime((row as TransactionReportRow).dateTime) },
        { key: "type", label: "Type" },
        { key: "amount", label: "Amount", render: (row) => formatCurrency((row as TransactionReportRow).amount) },
        { key: "payer", label: "Payer", render: (row) => <UserCell user={(row as TransactionReportRow).payer} /> },
        { key: "recipient", label: "Recipient", render: (row) => <UserCell user={(row as TransactionReportRow).recipient} /> },
        { key: "status", label: "Status", render: (row) => <StatusCell status={(row as TransactionReportRow).status} /> },
      ];
    case "platformRevenue":
      return [
        { key: "transactionId", label: "Transaction Id" },
        { key: "dateTime", label: "Date & Time", render: (row) => formatDateTime((row as RevenueReportRow).dateTime) },
        { key: "revenueSource", label: "Revenue Source" },
        { key: "amount", label: "Amount", render: (row) => formatCurrency((row as RevenueReportRow).amount) },
        { key: "user", label: "User", render: (row) => <UserCell user={(row as RevenueReportRow).user} /> },
        { key: "description", label: "Description" },
      ];
    case "payouts":
      return [
        { key: "payoutId", label: "Payout Id" },
        { key: "dateTime", label: "Date & Time", render: (row) => formatDateTime((row as PayoutReportRow).dateTime) },
        { key: "bidderId", label: "Bidder Id" },
        { key: "bidder", label: "Bidder Name", render: (row) => <UserCell user={(row as PayoutReportRow).bidder} /> },
        { key: "amount", label: "Amount", render: (row) => formatCurrency((row as PayoutReportRow).amount) },
        { key: "method", label: "Method" },
        { key: "status", label: "Status", render: (row) => <StatusCell status={(row as PayoutReportRow).status} /> },
      ];
    case "userRegistrations":
      return [
        { key: "userId", label: "User Id" },
        { key: "user", label: "User Name", render: (row) => <UserCell user={(row as UserRegistrationReportRow).user} /> },
        { key: "email", label: "Email Id" },
        { key: "registrationDate", label: "Registration Date", render: (row) => formatDateTime((row as UserRegistrationReportRow).registrationDate) },
        { key: "userType", label: "User Type" },
        { key: "location", label: "Location" },
        { key: "referralSource", label: "Referral Source" },
      ];
    case "jobPostings":
      return [
        { key: "jobId", label: "Job Id" },
        { key: "jobTitle", label: "Job Title" },
        { key: "client", label: "Client", render: (row) => <UserCell user={(row as JobPostingReportRow).client} /> },
        { key: "postedDate", label: "Posted Date", render: (row) => formatDateTime((row as JobPostingReportRow).postedDate) },
        { key: "budget", label: "Budget", render: (row) => formatCurrency((row as JobPostingReportRow).budget) },
        { key: "applicants", label: "Applicants" },
        { key: "status", label: "Status", render: (row) => <StatusCell status={(row as JobPostingReportRow).status} /> },
      ];
    case "disputes":
      return [
        { key: "reportId", label: "Report Id" },
        { key: "jobId", label: "Job Id" },
        { key: "jobTitle", label: "Job Title" },
        { key: "reportedBy", label: "Reported By", render: (row) => <UserCell user={(row as DisputeReportRow).reportedBy} /> },
        { key: "reason", label: "Reason" },
        { key: "createdAt", label: "Created On", render: (row) => formatDateTime((row as DisputeReportRow).createdAt) },
        { key: "status", label: "Status", render: (row) => <StatusCell status={(row as DisputeReportRow).status} /> },
      ];
    default:
      return [];
  }
};

const Reports: React.FC = () => {
  const [reportsData, setReportsData] = useState<ReportsData>(emptyReportsData);
  const [activeTab, setActiveTab] = useState<ReportTabId>("transactions");
  const [statusFilter, setStatusFilter] = useState("all");
  const [secondaryFilter, setSecondaryFilter] = useState("all");
  const [dateRangeFilter, setDateRangeFilter] = useState("all");
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  const baseRows = useMemo(() => getRowsForTab(reportsData, activeTab), [reportsData, activeTab]);

  const {
    searchTerm,
    setSearchTerm,
    filteredAndSortedRows,
    requestSort,
    sortConfig,
  } = useReports(baseRows);

  useEffect(() => {
    setLoading(true);
    fetchReportsData()
      .then((data) => {
        setReportsData(data);
        setErrorMessage("");
      })
      .catch((error) => {
        console.error("Reports fetch failed:", error);
        setErrorMessage("Unable to load reports from Supabase.");
      })
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    setStatusFilter("all");
    setSecondaryFilter("all");
    setDateRangeFilter("all");
    setSearchTerm("");
  }, [activeTab, setSearchTerm]);

  const filteredRows = filteredAndSortedRows.filter((row) => {
    if (statusFilter !== "all" && getStatusFromRow(row) !== statusFilter) {
      return false;
    }

    if (secondaryFilter !== "all" && getSecondaryValue(row, activeTab) !== secondaryFilter) {
      return false;
    }

    if (!isWithinRange(getDateFromRow(row), dateRangeFilter)) {
      return false;
    }

    return true;
  });

  const secondaryOptions = useMemo(() => {
    return Array.from(
      new Set(baseRows.map((row) => getSecondaryValue(row, activeTab)).filter(Boolean))
    )
      .sort()
      .map((value) => ({
        label: value,
        value,
      }));
  }, [baseRows, activeTab]);

  const columns = useMemo(() => getColumns(activeTab), [activeTab]);
  const activeTabLabel = tabs.find((tab) => tab.id === activeTab)?.label ?? "Report";

  return (
    <div
      style={{
        width: "100%",
        display: "flex",
        flexDirection: "column",
        gap: 18,
        fontFamily: "'DM Sans', 'Helvetica Neue', sans-serif",
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 22,
          borderBottom: "1px solid #E8EDF2",
          overflowX: "auto",
        }}
      >
        {tabs.map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            style={{
              border: "none",
              borderBottom: activeTab === tab.id ? "2px solid #EA580C" : "2px solid transparent",
              background: "transparent",
              color: activeTab === tab.id ? "#EA580C" : "#334155",
              fontWeight: activeTab === tab.id ? 700 : 500,
              padding: "0 0 12px",
              cursor: "pointer",
              whiteSpace: "nowrap",
              fontFamily: "inherit",
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <ReportToolbar
        searchTerm={searchTerm}
        onSearch={setSearchTerm}
        statusFilter={statusFilter}
        onStatusChange={setStatusFilter}
        secondaryFilter={secondaryFilter}
        onSecondaryFilterChange={setSecondaryFilter}
        secondaryPlaceholder={getSecondaryPlaceholder(activeTab)}
        secondaryOptions={secondaryOptions}
        dateRangeFilter={dateRangeFilter}
        onDateRangeChange={setDateRangeFilter}
      />

      <ReportSummaryBar
        title={getReportTitle(activeTab)}
        items={getSummaryItems(activeTab, filteredRows)}
        onExportCsv={() =>
          exportCsv(`weera-${activeTabLabel.toLowerCase().replace(/\s+/g, "-")}-report`, filteredRows)
        }
      />

      {errorMessage && (
        <div
          style={{
            padding: 14,
            border: "1px solid #FCA5A5",
            borderRadius: 10,
            color: "#B91C1C",
            background: "#FEF2F2",
            fontSize: 14,
          }}
        >
          {errorMessage}
        </div>
      )}

      {loading ? (
        <div
          style={{
            background: "#fff",
            border: "1px solid #E8EDF2",
            borderRadius: 16,
            padding: 48,
            color: "#64748B",
            textAlign: "center",
          }}
        >
          Loading reports from Supabase...
        </div>
      ) : (
        <ReportTable
          rows={filteredRows}
          columns={columns}
          onSort={requestSort}
          sortConfig={sortConfig}
          rowsPerPage={10}
          emptyLabel={`No ${activeTabLabel.toLowerCase()} report data found in Supabase`}
        />
      )}
    </div>
  );
};

export default Reports;
